_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet2Detector" #"GeneralizedRCNN" #
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"  
  WEIGHTS: "./output/fsod/finetune_dir/V-19-eSE-slim-FPN-ms-4x.pth" 
  VOVNET:
    CONV_BODY: "V-19-slim-eSE" #"V-19-eSE" #"V-19-slim-eSE"
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 3
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
    OUT_CHANNELS: 128
  ROI_HEADS:
    NAME: "CustomCascadeROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"] #["p3", "p4", "p5", "p6", "p7"]
    IOU_THRESHOLDS: [0.6]
    NMS_THRESH_TEST: 0.9 #  0.7 
  ROI_BOX_CASCADE_HEAD:
    IOUS: [0.6] #[0.5, 0.6, 0.7] #[0.6, 0.7, 0.8]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    POOLER_RESOLUTION: 8 #池化成7x7 7 
    CLS_AGNOSTIC_BBOX_REG: True
    MULT_PROPOSAL_SCORE: True
  CENTERNET:
    REG_WEIGHT: 1.
    NOT_NORM_REG: True
    ONLY_PROPOSAL: True
    WITH_AGN_HM: True
    INFERENCE_TH: 0.00001
    PRE_NMS_TOPK_TRAIN: 4000
    POST_NMS_TOPK_TRAIN: 2000 # 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 256 # 256
    NMS_TH_TRAIN:  0.9 #0.9
    NMS_TH_TEST:  0.6 # 0.9
    POS_WEIGHT: 0.5
    NEG_WEIGHT: 0.5
    IGNORE_HIGH_FP: 0.85
    NUM_CLASSES: 1
    FPN_STRIDES: [8, 16, 32]
    IN_FEATURES: ['p3', 'p4', 'p5']
    SOI: [[0, 64], [48, 192], [128, 1000000]]
    NUM_CLS_CONVS: 1
    NUM_BOX_CONVS: 1
DATASETS:
  TRAIN: ("coco_2017_train_stone",)
  TEST: ("coco_2017_val_stone",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  STEPS:   (10000,11000) #
  MAX_ITER:  12000  # 3100
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 100
  WARMUP_FACTOR: 0.00025
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  FS:
    FEW_SHOT: False # True #False,fine-tune
    SUPPORT_WAY: 1
    SUPPORT_SHOT: 24
  MIN_SIZE_TRAIN: (200, 240, 280, 320, 360, 400, 440) #(256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608) #(200, 240, 280, 320, 360, 400, 440) #(400, ) #(220, 220) #(240, 272, 304, 336, 368, 400) #(440, 472, 504, 536, 568, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 320 # 400 # 620 # 370 # 460 430 400
  MAX_SIZE_TEST: 1000 
# TEST:
#   EVAL_PERIOD: 100
OUTPUT_DIR: './output/fsod/finetune_dir/vovnet_25shot'

